### ISSUE TITLE
`prepare.sh`: submodule update --init "error" for EDK2

### ISSUE THREAD

**Issue by tylerfanelli** [stefano-garzarella/snp-svsm-vtpm#8]
When running `prepare.sh,` I'm unable to clone all of `edk2` due wanting a sign-in from github.

```
make[1]: Leaving directory '/home/tfanelli/snp-svsm-vtpm/snp-svsm-vtpm/qemu/build'
+ popd
~/snp-svsm-vtpm/snp-svsm-vtpm
+ pushd /home/tfanelli/snp-svsm-vtpm/snp-svsm-vtpm/edk2
~/snp-svsm-vtpm/snp-svsm-vtpm/edk2 ~/snp-svsm-vtpm/snp-svsm-vtpm
+ git submodule update --init

...[snip]...

Cloning into '/home/tfanelli/snp-svsm-vtpm/snp-svsm-vtpm/edk2/UnitTestFrameworkPkg/Library/SubhookLib/subhook'...
Username for 'https://github.com':
```

This shouldn't be prompted on a simple clone, correct?

**Comment by tylerfanelli** [comment]
It seems I'm only seeing this issue with `SubhookLib`.

**Comment by osteffenrh** [comment]
Upstream EDK2 has an issue currently: The subhook repo disappeared from github.

**Comment by stefano-garzarella** [comment]
> This shouldn't be prompted on a simple clone, correct?

Yep!

> Upstream EDK2 has an issue currently: The subhook repo disappeared from github.

Tracked here: https://github.com/tianocore/edk2/issues/6398
It looks like they created a clone, I'll try to update our fork too.

**Comment by stefano-garzarella** [comment]
@tylerfanelli I pushed a new commit that should fix the issue (this is the fix upstream https://github.com/coconut-svsm/edk2/pull/4), please let me know if it works (or not).

**Comment by tylerfanelli** [comment]
It seems with the following diff:
```
diff --git a/.gitmodules b/.gitmodules
index 3c62123..b197cad 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,7 +1,7 @@
 [submodule "edk2"]
        path = edk2
        url = https://github.com/stefano-garzarella/edk2.git
-       branch = svsm
+       branch = fix-subhook
 [submodule "kbs/reference-kbs"]
        path = kbs/reference-kbs
        url = https://github.com/stefano-garzarella/reference-kbs.git
```

Did not fix the issue for me.

**Comment by tylerfanelli** [comment]
@stefano-garzarella sorry, I noticed you also rebased this repository. I've rebased on your `main` branch and it works.
